language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - TOOLKIT=true
  - TOOLKIT=false

matrix:
  exclude:
    - os: osx
      env: TOOLKIT=true
    - os: linux
      compiler: clang
      env: TOOLKIT=true
script: |
  if [[ $TOOLKIT = true ]]; then 
    bash <(curl -s https://runtimeverification.com/toolkit/docker/bash) nightly-2018-08-27;
  else
    ./autogen.sh && ./configure && make;
  fi
